AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda with Cloudwatch Event to create a Technical Report of Baxter Cloud Compliance.

Parameters:
  LambdaBucket:
    Type: String
    Default: blah 
    Description: S3 bucket for the code upload

  LambdaRegion:
    Type: String
    Default: reg
    Description: S3 bucket for the code upload

Resources:
  TestReportLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Role: "arn:aws:iam::770765425423:role/TestLambda"
      Runtime: python3.8
      FunctionName: TestReportLambda
      Description: Testing
      Handler: "TestFunctionCF.lambda_handler"
      Timeout: 300
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: "TestFunctionCF.zip"
        

Outputs:
  TestReportLambda:
    Description: Function Name
    Value: !Ref TestReportLambda
